import io.vertx.core.Vertx;
import io.vertx.ext.bridge.BridgeOptions;
import io.vertx.ext.bridge.PermittedOptions;
import io.vertx.ext.eventbus.bridge.tcp.TcpEventBusBridge;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        Vertx vertx = Vertx.vertx();

        // Starting Dummy verticle that is sending and receiving message
        vertx.deployVerticle(ReceivingVerticle.class.getName());
        vertx.deployVerticle(SendingVerticle.class.getName());


        TcpEventBusBridge bridge = TcpEventBusBridge.create(
                vertx,
                new BridgeOptions()
                        .addInboundPermitted(new PermittedOptions().setAddress("in"))
                        .addOutboundPermitted(new PermittedOptions().setAddress("out")));

        bridge.listen(7000, res -> {
            if (res.succeeded()) {
                System.out.println("Bridge started");
            } else {
                System.exit(1);
            }
        });
    }
}
